model: !!python/name:sklearn.ensemble.RandomForestClassifier
ModelKeywordArguments:
  # class_weight: "balanced"
  random_state: 573
  n_jobs: -1
VectorizationArguments:
VectorizationKeywordArguments:
TokenizerArguments:
TokenizerKeywordArguments:
  return_tensors: pt
  max_length: 512
  truncation: True
