name: SADTech
channels:
  - pytorch
  - fastai
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pip=23.*
  - black
  - mypy
  - pytorch=2.*
  - torchaudio
  - plotnine=0.*
  - nltk=3.*
  - stanfordcorenlp=3.*
  - stanza=1.*
  - spacy=3.*
  - scipy
  - numpy
  - pandas=2.*
  - pandas-stubs
  - scikit-learn=1.*
  - imbalanced-learn=0.*
  - transformers=4.*
  - accelerate
  - sentencepiece=0.*
  - librosa=0.*
  - pysoundfile>=0.12.1
  - ftfy=6.*
  - flax=0.*
  - hydra-core=1.*
  - pyyaml=6.*
  - types-pyyaml
  - openpyxl
  - types-openpyxl
  - lxml-stubs
  - types-Pillow
  - types-requests
  - types-setuptools
  - types-tabulate
  - mkl < 2022
  - pip:
    - hydra-submitit-launcher
    - types-pywin32
    - types-tqdm
