name: SADTech
channels:
  - fastai
  - conda-forge
  - defaults
dependencies:
  - python=3.9.*
  - pytorch=2.*
  - black
  - mypy
  - plotnine=0.10.*
  - nltk=3.*
  - stanfordcorenlp=3.*
  - stanza=1.*
  - spacy=3.*
  - scipy
  - numpy
  - pandas=2.*
  - scikit-learn=1.*
  - transformers=4.*
  - sentencepiece=0.*
  - fairseq=0.*
  - ftfy=6.*
  - flax=0.*
  - pyyaml=6.*
  - types-pyyaml=6.*
