name: gpu_SADTech
channels:
  - pytorch
  - nvidia
  - fastai
  - conda-forge
  - defaults
dependencies:
  - python=3.9.*
  - pip=23.*
  - pytorch=2.*
  - pytorch-cuda=11.*
  - black
  - mypy
  - plotnine=0.*
  - nltk=3.*
  - stanfordcorenlp=3.*
  - stanza=1.*
  - spacy=3.*
  - scipy
  - numpy
  - pandas=2.*
  - pandas-stubs
  - scikit-learn=1.*
  - imbalanced-learn=0.*
  - transformers=4.*
  - accelerate
  - sentencepiece=0.*
  - hydra-core=1.*
  - ftfy=6.*
  - flax=0.*
  - pyyaml=6.*
  - types-pyyaml
  - lxml-stubs
  - types-openpyxl
  - types-Pillow
  - types-requests
  - types-setuptools
  - types-tabulate
  - pip:
    - types-pywin32
    - types-tqdm
