name: gpu_SADTech
channels:
  - pytorch
  - nvidia
  - fastai
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pip=23.*
  - black
  - mypy
  - pytorch=2.*
  - pytorch-cuda=11.*
  - torchaudio
  - matplotlib
  - seaborn
  - nltk=3.*
  - stanfordcorenlp=3.*
  - stanza=1.*
  - spacy=3.*
  - gensim>=4.3
  - fasttext>=0.9
  - scipy
  - numpy
  - pandas=2.*
  - pandas-stubs
  - scikit-learn=1.*
  - imbalanced-learn=0.*
  - transformers=4.*
  - accelerate
  - sentencepiece=0.*
  - librosa=0.*
  - pysoundfile>=0.12.1
  - ftfy=6.*
  - flax=0.*
  - nlpaug=1.*
  - hydra-core>=1.3
  - submitit>=1.3.3
  - pyyaml=6.*
  - types-pyyaml
  - openpyxl
  - types-openpyxl
  - lxml-stubs
  - types-Pillow
  - types-pywin32
  - types-requests
  - types-setuptools
  - types-tabulate
  - types-tqdm
  - pip:
    - hydra-submitit-launcher
