defaults:
  - text/vectorizer: TransformerLayerVectorizer
  # - audio/vectorizer: ColumnSelector
  # - /classifiers@classifier: rf
  - _self_
text:
  vectorizer: ???
audio_col: ???
# audio:
#   vectorizer: ???
joint: []
classifier: ???
