# @package _global_
defaults:
  - /launcher_config/slurm 
  - _self_
cleaned_override_dirname: ${lang}/text_only/${slash2under:${pipeline.text.vectorizer.language_model}}/${clean_path:${hydra:job.override_dirname}}
# hydra:
#   job:
#     config:
#       override_dirname:
#         exclude_keys:
#           - pipeline
#           - pipeline.audio.column_name
#           - dataset
#           - debug
#           - launcher_config
#           - lang
#           - seed
#           # - pipeline.classifier
#         item_sep: ","
#         kv_sep: "="
