defaults:
  - _self_
model_path: ai4bharat/MultiIndicParaphraseGenerationSS
model:
  _target_: transformers.AutoModelForSeq2SeqLM
  cls: ${..model_path}
tokenizer:
  _target_: transformers.AutoTokenizer
  cls: ${..model_path}
  bos_token: "<s>"
  eos_token: "</s>"
  pad_token: "<pad>"
  use_fast: False
generation_config:
  _target_: 
