TextTransformers:
  - name: "xlm_roberta_base"
    class: !!python/name:pipeline_transformers.vectorizers.TransformerLayerVectorizer
    args: []
    kwargs:
AudioTransformers: []
Classifier:
   class: !!python/name:sklearn.ensemble.RandomForestClassifier
   args: []
   kwargs:
      random_state: !!python/name:common.GLOBAL_SEED
      n_jobs: -1
